using System;
using System.IO;
using System.Text;

namespace NeuralPipelineStudio.Core
{
    public static class ShaderGenerator
    {
        public static void GenerateChainShaders(string targetShaderDir, int preCycles, int postCycles, float downRatio, float upRatio, bool vramOptimized)
        {
            if (!Directory.Exists(targetShaderDir)) return;

            string fmt = vramOptimized ? "RGBA8" : "RGBA16F";
            string preCode = GenerateChainCode(preCycles, downRatio, upRatio, fmt, true);
            string postCode = GenerateChainCode(postCycles, downRatio, upRatio, fmt, false);

            string prePath = Path.Combine(targetShaderDir, "lumenite_IterativeDownUpChain_Pre.fx");
            string postPath = Path.Combine(targetShaderDir, "lumenite_IterativeDownUpChain.fx");

            File.WriteAllText(prePath, preCode, Encoding.UTF8);
            File.WriteAllText(postPath, postCode, Encoding.UTF8);
        }

        private static string GenerateChainCode(int cycles, float downRatio, float upRatio, string format, bool isPre)
        {
            string prefix = isPre ? "Pre" : "Post";
            string chainName = isPre ? "Pre-Downscale Chain" : "Post-Neural Output Chain";
            string techName = isPre ? "Lumenite_IterativeDownUpChain_Pre" : "Lumenite_IterativeDownUpChain";

            var sb = new StringBuilder();
            sb.AppendLine("/*");
            sb.AppendLine($"    lumenite_IterativeDownUpChain_{(isPre ? "Pre" : "")}.fx");
            sb.AppendLine($"    Auto-generated by Neural Pipeline Studio v2.0 ({cycles} Iterative Cycles)");
            sb.AppendLine($"    Format: {format} | Downscale: {downRatio:F2}x | Upscale: {upRatio * 100f:F0}%");
            sb.AppendLine("*/");
            sb.AppendLine();
            sb.AppendLine("#include \"ReShade.fxh\"");
            sb.AppendLine();
            sb.AppendLine($"#define CHAIN_CYCLES {cycles}");
            sb.AppendLine($"#define DOWN_RATIO {downRatio.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture)}");
            sb.AppendLine($"#define DOWN_WIDTH int(BUFFER_WIDTH * DOWN_RATIO)");
            sb.AppendLine($"#define DOWN_HEIGHT int(BUFFER_HEIGHT * DOWN_RATIO)");
            sb.AppendLine();
            sb.AppendLine("// UI Controls");
            sb.AppendLine($"uniform float CYCLE_CONTRAST < ui_type = \"slider\"; ui_min = 0.9; ui_max = 1.3; ui_step = 0.005; ui_label = \"{chainName} Contrast\"; > = 1.02;");
            sb.AppendLine($"uniform float CYCLE_CLARITY < ui_type = \"slider\"; ui_min = 0.0; ui_max = 1.0; ui_step = 0.01; ui_label = \"{chainName} Clarity\"; > = 0.20;");
            sb.AppendLine($"uniform float CYCLE_SHARPNESS < ui_type = \"slider\"; ui_min = 0.0; ui_max = 1.0; ui_step = 0.01; ui_label = \"{chainName} Sharpness\"; > = 0.35;");
            sb.AppendLine();
            sb.AppendLine("// Shared Ping-Pong Textures (VRAM Optimized Buffer Recycling)");
            sb.AppendLine($"texture TexDownA_{prefix} {{ Width = DOWN_WIDTH; Height = DOWN_HEIGHT; Format = {format}; }};");
            sb.AppendLine($"texture TexDownB_{prefix} {{ Width = DOWN_WIDTH; Height = DOWN_HEIGHT; Format = {format}; }};");
            sb.AppendLine($"texture TexFullA_{prefix} {{ Width = BUFFER_WIDTH; Height = BUFFER_HEIGHT; Format = {format}; }};");
            sb.AppendLine($"texture TexFullB_{prefix} {{ Width = BUFFER_WIDTH; Height = BUFFER_HEIGHT; Format = {format}; }};");
            sb.AppendLine();
            sb.AppendLine($"sampler sDownA_{prefix} {{ Texture = TexDownA_{prefix}; }};");
            sb.AppendLine($"sampler sDownB_{prefix} {{ Texture = TexDownB_{prefix}; }};");
            sb.AppendLine($"sampler sFullA_{prefix} {{ Texture = TexFullA_{prefix}; }};");
            sb.AppendLine($"sampler sFullB_{prefix} {{ Texture = TexFullB_{prefix}; }};");
            sb.AppendLine();
            sb.AppendLine("#define DOWN_TEXEL float2(1.0 / DOWN_WIDTH, 1.0 / DOWN_HEIGHT)");
            sb.AppendLine();

            sb.AppendLine("// Downscale Filter: 13-tap Dual-Grid Box");
            sb.AppendLine($"float4 PS_Downscale_{prefix}(float4 vpos : SV_Position, float2 uv : TEXCOORD, sampler sInput) : SV_Target");
            sb.AppendLine("{");
            sb.AppendLine("    float2 tx = DOWN_TEXEL;");
            sb.AppendLine("    float4 o = tx.xyxy * float2(-1.0, 1.0).xxyy;");
            sb.AppendLine("    float4 color = tex2D(sInput, uv) * 4.0;");
            sb.AppendLine("    color += tex2D(sInput, uv - o.zy);");
            sb.AppendLine("    color += tex2D(sInput, uv - o.wy);");
            sb.AppendLine("    color += tex2D(sInput, uv + o.zw);");
            sb.AppendLine("    color += tex2D(sInput, uv + o.ww);");
            sb.AppendLine("    color += tex2D(sInput, uv - o.xy * 0.5) * 2.0;");
            sb.AppendLine("    color += tex2D(sInput, uv + o.zy * 0.5) * 2.0;");
            sb.AppendLine("    color += tex2D(sInput, uv + o.xw * 0.5) * 2.0;");
            sb.AppendLine("    color += tex2D(sInput, uv - o.zw * 0.5) * 2.0;");
            sb.AppendLine("    return color / 16.0;");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("// Upscale Filter: Pure Luminance-Conserving Catmull-Rom Spline");
            sb.AppendLine($"float4 PS_CatmullRom_{prefix}(float4 vpos : SV_Position, float2 uv : TEXCOORD, sampler sInput) : SV_Target");
            sb.AppendLine("{");
            sb.AppendLine("    float2 pos = uv * float2(DOWN_WIDTH, DOWN_HEIGHT) - 0.5;");
            sb.AppendLine("    float2 f = frac(pos);");
            sb.AppendLine("    float2 tc = (pos - f + 0.5) * DOWN_TEXEL;");
            sb.AppendLine("    float2 w1 = 1.0 + f * f * (-2.5 + 1.5 * f);");
            sb.AppendLine("    float2 w2 = f * (0.5 + f * (2.0 - 1.5 * f));");
            sb.AppendLine("    float2 w12 = max(w1 + w2, 0.0001);");
            sb.AppendLine("    float2 tc12 = tc + (w2 / w12) * DOWN_TEXEL;");
            sb.AppendLine("    return tex2D(sInput, tc12);");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine($"float4 PS_CatmullRom_{prefix}_Final(float4 vpos : SV_Position, float2 uv : TEXCOORD, sampler sInput) : SV_Target");
            sb.AppendLine("{");
            sb.AppendLine("    float2 pos = uv * float2(DOWN_WIDTH, DOWN_HEIGHT) - 0.5;");
            sb.AppendLine("    float2 f = frac(pos);");
            sb.AppendLine("    float2 tc = (pos - f + 0.5) * DOWN_TEXEL;");
            sb.AppendLine("    float2 w1 = 1.0 + f * f * (-2.5 + 1.5 * f);");
            sb.AppendLine("    float2 w2 = f * (0.5 + f * (2.0 - 1.5 * f));");
            sb.AppendLine("    float2 w12 = max(w1 + w2, 0.0001);");
            sb.AppendLine("    float2 tc12 = tc + (w2 / w12) * DOWN_TEXEL;");
            sb.AppendLine("    float4 color = tex2D(sInput, tc12);");
            sb.AppendLine("    float4 sharp = tex2D(sInput, uv);");
            sb.AppendLine("    color = lerp(color, sharp, saturate(CYCLE_SHARPNESS * 0.25));");
            sb.AppendLine("    color.rgb = lerp(float3(0.5, 0.5, 0.5), color.rgb, CYCLE_CONTRAST);");
            sb.AppendLine("    return color;");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("// Iterative Cycle Passes");
            for (int i = 0; i < cycles; i++)
            {
                string downSrc = (i == 0) ? "ReShade::sBackBuffer" : $"sFull{((i % 2 == 1) ? "A" : "B")}_{prefix}";
                string downDst = $"TexDown{((i % 2 == 0) ? "A" : "B")}_{prefix}";
                string upSrc = $"sDown{((i % 2 == 0) ? "A" : "B")}_{prefix}";
                string upDst = (i == cycles - 1) ? "" : $"TexFull{((i % 2 == 0) ? "A" : "B")}_{prefix}";
                string upFunc = (i == cycles - 1) ? $"PS_CatmullRom_{prefix}_Final" : $"PS_CatmullRom_{prefix}";

                sb.AppendLine($"float4 PS_Down_{prefix}_{i}(float4 p : SV_Position, float2 uv : TEXCOORD) : SV_Target {{ return PS_Downscale_{prefix}(p, uv, {downSrc}); }}");
                sb.AppendLine($"float4 PS_Up_{prefix}_{i}(float4 p : SV_Position, float2 uv : TEXCOORD) : SV_Target {{ return {upFunc}(p, uv, {upSrc}); }}");
            }
            sb.AppendLine();

            sb.AppendLine($"technique {techName}");
            sb.AppendLine("{");
            for (int i = 0; i < cycles; i++)
            {
                string downDst = $"TexDown{((i % 2 == 0) ? "A" : "B")}_{prefix}";
                string upDst = (i == cycles - 1) ? "" : $"TexFull{((i % 2 == 0) ? "A" : "B")}_{prefix}";

                sb.AppendLine($"    pass Cycle_{i}_Down {{ VertexShader = PostProcessVS; PixelShader = PS_Down_{prefix}_{i}; RenderTarget = {downDst}; }}");
                if (string.IsNullOrEmpty(upDst))
                    sb.AppendLine($"    pass Cycle_{i}_UpFinal {{ VertexShader = PostProcessVS; PixelShader = PS_Up_{prefix}_{i}; }}");
                else
                    sb.AppendLine($"    pass Cycle_{i}_Up {{ VertexShader = PostProcessVS; PixelShader = PS_Up_{prefix}_{i}; RenderTarget = {upDst}; }}");
            }
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
